name: Build & Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      TF_CLOUD_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17


      - name: Build Lambda JAR
        run: mvn clean package

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_CLOUD_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_CLOUD_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          # AWS Credentials
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          # Terraform Cloud API Token
          TF_CLOUD_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

          # Variáveis do Terraform para Lambda
          TF_VAR_aws_region: ${{ secrets.TF_VAR_AWS_REGION }}
          TF_VAR_service_name: ${{ secrets.TF_VAR_SERVICE_NAME }}
          TF_VAR_db_host: ${{ secrets.TF_VAR_DB_HOST }}
          TF_VAR_db_user: ${{ secrets.TF_VAR_DB_USER }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_db_name: ${{ secrets.TF_VAR_DB_NAME }}
          TF_VAR_jwt_secret: ${{ secrets.TF_VAR_JWT_SECRET }}
          TF_VAR_jwt_ttl_seconds: ${{ secrets.TF_VAR_JWT_TTL_SECONDS }}